name: mysleep
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  android_alarm_manager_plus: ^2.0.7+1
  animation_list: ^2.2.1
  bottom_nav_bar: ^1.0.3
  cached_network_image: ^3.2.3
  calendar_date_picker2: ^0.2.5
  carousel_slider: ^4.1.1
  cool_dropdown: ^1.4.2
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  easy_loading: ^0.0.4
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_date_pickers: ^0.4.0
  flutter_datetime_picker: ^1.5.1
  flutter_easyloading: ^3.0.5
  flutter_launcher_icons: ^0.11.0
  flutter_otp_text_field: 1.0.0
  flutter_slidable: ^1.3.2
  flutter_snake_navigationbar: ^0.6.1
  flutter_spinkit: ^5.1.0
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  get: 4.6.5
  get_it: ^7.2.0
  google_maps_flutter: ^2.2.2
  image_picker: ^0.8.6
  infinite_carousel: ^1.0.2
  intl: ^0.17.0
  persistent_bottom_nav_bar: ^4.0.2
  shared_preferences: ^2.0.15
  timer_builder: ^2.0.0

dev_dependencies:
  flutter_launcher_icons: "^0.11.0"
  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/png/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/png/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/png/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/png/logo.png"

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/png/

  fonts:
    - family: interMedium
      fonts:
        - asset: assets/fonts/inter/Inter-Medium.ttf
    - family: interBold
      fonts:
        - asset: assets/fonts/inter/Inter-Bold.ttf
